/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package application;

import java.awt.Canvas;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.util.ArrayList;
import main.Load;
import bill.Report;
import java.awt.Graphics2D;
import java.util.Date;
import javax.swing.JPanel;

/**
 *
 * @author ASUS
 */
public class ReportFrame extends javax.swing.JFrame {

    /**
     * Creates new form ReportFrame
     */
    public ReportFrame() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        totalLabel = new javax.swing.JLabel();
        profitLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Báo cáo");

        cbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tuần gần nhất", "Tháng gần nhất", "Quý gần nhất", "Năm gần nhất" }));
        cbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Doanh thu: ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Lợi nhuận:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        totalLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        profitLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbox, javax.swing.GroupLayout.Alignment.TRAILING, 0, 842, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalLabel)
                            .addComponent(jLabel3)
                            .addComponent(profitLabel))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(cbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(profitLabel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxActionPerformed
        // TODO add your handling code here:
        int selectString = cbox.getSelectedIndex();
        if(selectString == 1) {
            ArrayList<Report> yList = Load.getReport(selectString);
            
            int total = 0, profit = 0;
            for(Report r : yList){
                total += r.getTotal();
                profit += r.getProfit();
            }
            totalLabel.setText(total + " VNĐ");
            profitLabel.setText(profit + " VNĐ");
            
            
            MyCanvas c = new MyCanvas(yList);
            c.show(true);
            this.add(c);
        }
        
        
    }//GEN-LAST:event_cboxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReportFrame().setVisible(true);
            }
        });
    }
    
    class MyCanvas extends JPanel {
        
        private ArrayList<Report> List;
        //private ArrayList<Date> dates;
        private ArrayList<Integer> tList = new ArrayList<>();
        private ArrayList<Integer> pList = new ArrayList<>();
        public MyCanvas(ArrayList<Report> list) {
            setBackground(Color.WHITE);
            
            setBounds(50, 100, 600, 450);
            
            List = list;
            System.err.println(List.toString());
            
            for(int i = 0; i < 31; i++) {
                boolean isAdd = false;
                for(Report r : List) {
                    if(r.getDate().getDate() == (i+1)) {
                        System.err.println(r.getDate().getDate());
                        tList.add(r.getTotal());
                        pList.add(r.getProfit());
                        isAdd = true;
                        break;
                    }
                }
                if (!isAdd) {
                    tList.add(0);
                    pList.add(0);
                }
            }
        }
        
        @Override
        public void paintComponent(Graphics graphics) {            
            
            super.paintComponent(graphics);
            Graphics2D g = (Graphics2D) graphics;
            int startX = 50;
            int startY = 50;
            int endX = 600;
            int endY = 400;
            int unitX = (endX - startX) / 31;
            int unitY = (endY - startY) / 50;
            int prevX = startX;
            int prevY = endY;
            
            g.setColor(Color.BLACK);
            g.drawLine(startX, startY, startX, endY);
            g.drawLine(startX, endY, endX, endY);
            
            g.setColor(Color.BLUE);
            for (Integer y : tList) {
                y = y/50000;
                g.drawLine(prevX, prevY, prevX += unitX, prevY = endY - (y * unitY));
                System.err.print(prevY + "\t");
            }
            
            prevX = startX;
            prevY = endY;
            g.setColor(Color.GREEN);
            for (Integer y : pList) {
                y = y/50000;
                g.drawLine(prevX, prevY, prevX += unitX, prevY = endY - (y * unitY));
                System.err.println(prevY);
                
            }
        }
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel profitLabel;
    private javax.swing.JLabel totalLabel;
    // End of variables declaration//GEN-END:variables
}
